# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#
proxy:
  https:
    enabled: true
    hosts:
      - workshop.biosimspace.org
    letsencrypt:
      contactEmail: Christopher.Woods@bristol.ac.uk
rbac:
  enabled: true
singleuser:
  defaultUrl: "/lab"
  image:
    name: biosimspace/biosimspace-workshop
    tag: v3
  storage:
    type: none
  memory:
    limit: 5.0G
    guarantee: 1.0G
  cpu:
    limit: 10.0
    guarantee: 0.2
cull:
  timeout: 2400
  every: 600
prePuller:
  continuous:
    enabled: true
hub:
  config:
    JupyterHub:
      authenticator_class: tmpauthenticator.TmpAuthenticator

